## Data Analysts hate this new way of analysis

If anyone got clickbaited, I am extremely sorry and the title was simply meant as a joke.

The method most commonly used to get an overview of the data, describe() ,has a significant flaw.

It does not have any information on categorical data.

This new method ,however, does work for categorical data as well. It goes by the name of pandas_profiling.



## Dataset used for testing purpose

This dataset includes jobs put by NHS relating to doctors only between the period of March 2019 to October 2019.

[NHS jobs](https://www.kaggle.com/homelesssandwich/nhs-jobs)

In [1]:
import pandas as pd
import numpy as np
import time
nhs = pd.read_csv("jobs_raw.csv")
#To display all the columns
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

nhs.head()

job_title          job_reference  \
0     Trainee Advanced Clinical Practitioner       J180-A-19-286627   
1   Trust Doctor in Obstetrics & Gynaecology  259-TG-APROT-A-RLHO&G   
2   Fixed Term Consultant Urological Surgeon           179-MSC08-19   
3              Research Fellow in Psychiatry          263-MED19-007   
4  Clinical Teaching Fellow in Ophthalmology      259-MED1643381WXH   

                                            employer employer_postcode  \
0        Central Advertising - General Practitioners          CF37 1LB   
1                             Barts Health NHS Trust            E1 8PR   
2                  West Suffolk NHS Foundation Trust          IP33 2QZ   
3  Northumberland Tyne and Wear NHS Foundation Trust           NE3 3XT   
4                             Barts Health NHS Trust            E1 8PR   

                 department                                 location  \
0    Trinity Medical Centre                                Wakefield   
1  Obstetrics & Gynaecology  Obs & Gynae Medical Staff - RLH, London   
2                   Urology                         Bury St. Edmunds   
3                Psychiatry           St Nicholas Hospital, Gosforth   
4        Medical and Dental            Whipps Cross Hospital, London   

                        salary                  job_type  \
0                          TBC      Fixed term (2 years)   
1        £31,217 to £49,086 pa     Fixed term (6 months)   
2       £77,913 to £105,042 pa    Fixed term (12 months)   
3           £31,217 to £49,086  Fixed term (6-12 Months)   
4  £31,217 - £49,086 per annum                Fixed term   

               working_pattern                         pay_scheme  \
0                          TBC                              Other   
1                           40  Hospital Medical and Dental Staff   
2             11 Sessions/Week  Hospital Medical and Dental Staff   
3  Full Time 40 hours per week  Hospital Medical and Dental Staff   
4            32 hours per week                              Other   

         pay_band       staff_group                 specialty  \
0             NaN  Medical & Dental                       NaN   
1  Doctor - Other  Medical & Dental  Obstetrics & Gynaecology   
2      Consultant  Medical & Dental                   Urology   
3  Doctor - Other  Medical & Dental                Psychiatry   
4             NaN  Medical & Dental        Medical and Dental   

                                    full_description  json_salary_max  \
0  Trinity Medical Centre are currently seeking a...              NaN   
1  This Trust post is a Fixed Term Part Time Clin...          49086.0   
2  An opportunity has arisen for a Fixed Term Con...         105042.0   
3  Would you like to work in a CQC ‘Outstanding’ ...          49086.0   
4  Clinical Teaching Fellow in Ophthalmology 12 m...          49086.0   

   json_salary_min json_salary_unit            json_salary_value  \
0              NaN              NaN                          TBC   
1          31217.0             YEAR        £31,217 to £49,086 pa   
2          77913.0             YEAR       £77,913 to £105,042 pa   
3          31217.0             YEAR           £31,217 to £49,086   
4          31217.0             YEAR  £31,217 - £49,086 per annum   

           json_date_posted  \
0  2019-03-26T15:42:20+0000   
1  2019-03-25T18:15:16+0000   
2  2019-03-25T12:45:10+0000   
3  2019-03-25T13:45:57+0000   
4  2019-03-25T18:15:19+0000   

                                    json_description json_employment_type  \
0  &lt;p&gt;Trinity Medical Centre are currently ...            FULL_TIME   
1  &lt;p&gt;&lt;strong&gt;This Trust post is a Fi...            FULL_TIME   
2  &lt;p&gt;&lt;span&gt;An opportunity has arisen...            FULL_TIME   
3  &lt;p&gt;Would you like to work in a CQC ‘Outs...            FULL_TIME   
4  &lt;p&gt;&lt;strong&gt;Clinical Teaching Fello...            FULL_TIME   

                                      json_hire_name  \
0        

In [2]:
start = time.time()
nhs.describe()
end = time.time()
# To record time taken for execution
dtime = end - start
nhs.describe()

json_salary_max  json_salary_min      json_lat      json_lng
count     2.345500e+04     23455.000000  27482.000000  27482.000000
mean      7.733438e+04     56361.493967     52.210374     -1.249683
std       1.179852e+05     25451.474981      1.090745      1.296996
min       1.150000e+02       103.000000     49.183300     -5.548620
25%       4.807500e+04     31841.000000     51.468400     -2.214870
50%       7.466100e+04     49294.000000     51.764000     -1.207980
75%       1.050420e+05     77913.000000     53.134500     -0.161262
max       9.000000e+06    350000.000000     55.768800      1.743600

Before I proceed with the crazy , new and revolutionary way of data analysis ( Again, sorry!) , something that caught my eye was the min salary being 103 GBP, which makes no sense for a doctor's job. 

In [3]:
nhs[nhs["json_salary_min"] == nhs["json_salary_min"].min()]

job_title  job_reference  \
5553   Consultant Old Age Psychiatry    311-M003-19   
8853   Consultant Old Age Psychiatry    311-M009-19   
14052  Consultant Old Age Psychiatry  311-M003-19-A   
21429  Consultant Old Age Psychiatry  311-M003-19-B   

                                employer employer_postcode  \
5553   Pennine Care NHS Foundation Trust           OL6 7SR   
8853   Pennine Care NHS Foundation Trust           OL6 7SR   
14052  Pennine Care NHS Foundation Trust           OL6 7SR   
21429  Pennine Care NHS Foundation Trust           OL6 7SR   

               department                                 location  \
5553   Old Age Psychiatry                   The Meadows, Stockport   
8853   Old Age Psychiatry  Birch Hill Hospital, Rochdale, Rochdale   
14052  Old Age Psychiatry        The Meadows, Stockport, Stockport   
21429  Old Age Psychiatry        The Meadows, Stockport, Stockport   

                          salary   job_type  working_pattern  \
5553   Consultant £76,761 - £103  Permanent   40hrs (10PA's)   
8853   Consultant £76,761 - £103  Permanent  40hrs (10PA''s)   
14052  Consultant £76,761 - £103  Permanent   40hrs (10PA's)   
21429  Consultant £76,761 - £103  Permanent   40hrs (10PA's)   

                              pay_scheme    pay_band       staff_group  \
5553                               Other         NaN  Medical & Dental   
8853                               Other         NaN  Medical & Dental   
14052  Hospital Medical and Dental Staff  Consultant  Medical & Dental   
21429                              Other         NaN  Medical & Dental   

                specialty                                   full_description  \
5553   Old Age Psychiatry  Band & salary scale - Consultant £76,761 - £10...   
8853   Old Age Psychiatry  Band & salary scale - Consultant £76,761 - £10...   
14052  Old Age Psychiatry  JOB DISCRIPTION SUBJECT TO ROYAL COLLEGE APPRO...   
21429  Old Age Psychiatry  SUBJECT TO ROYAL COLLEGE APPROVAL Band & salar...   

       json_salary_max  json_salary_min json_salary_unit  \
5553           76761.0            103.0             YEAR   
8853           76761.0            103.0             YEAR   
14052          76761.0            103.0             YEAR   
21429          76761.0            103.0             YEAR   

               json_salary_value          json_date_posted  \
5553   Consultant £76,761 - £103  2019-04-24T14:00:44+0100   
8853   Consultant £76,761 - £103  2019-05-16T16:45:44+0100   
14052  Consultant £76,761 - £103  2019-07-05T17:15:37+0100   
21429  Consultant £76,761 - £103  2019-09-13T11:45:50+0100   

                                        json_description json_employment_type  \
5553   &lt;p&gt;&lt;strong&gt;Band &amp; salary scale...            FULL_TIME   
8853   &lt;p&gt;&lt;strong&gt;Band &amp; salary scale...            FULL_TIME   
14052  &lt;p&gt;&lt;em&gt;&lt;strong&gt;JOB DISCRIPTI...            FULL_TIME   
21429  &lt;p&gt;&lt;em&gt;&lt;strong&gt;SUBJECT TO RO...            FULL_TIME   

                          json_hire_name  \
5553   Pennine Care NHS Foundation Trust   
8853   Pennine Care NHS Foundation Trust   
14052  Pennine Care NHS Foundation Trust   
21429  Pennine Care NHS Foundation Trust   

                         json_address_locality json_address_postcode  \
5553                    The Meadows, Stockport               SK2 5EA   
8853   Birch Hill Hospital, Rochdale, Rochdale              OL12 9QB   
14052        The Meadows, Stockport, Stockport               SK2 5EA   
21429        The Meadows, Stockport, Stockport               SK2 5EA   

       json_lat  json_lng                     json_title json_closing_date  \
5553    53.3988  -2.11873  Consultant Old Age Psychiatry  28/05/2019 23:59   
8853    53.6431  -2.12634  Consultant Old Age Psychiatry  06/06/2019 23:59   
14052   53.3988  -2.11873  Consultant Old Age Psychiatry  16/08/2019 23:59   
21429   53.3988  -2.11873  Consultant Old Age Psychiatry  04/11/2019 23:59   

     

Ah this is most likely a mistake where it is supposed to be 103,000 GBP. This can be confirmed from the json_salary_value column with value given as £76,761 - £103.

I wonder what the maximum salary is then.

In [4]:
nhs[nhs["json_salary_max"] == nhs["json_salary_max"].max()]

job_title        job_reference  \
10741  Salaried GP Practitioner (2-4 sessions)  J180-SALARIEDGP0418   

                                          employer employer_postcode  \
10741  Central Advertising - General Practitioners          CF37 1LB   

               department  location  \
10741  Firstcare Practice  Hounslow   

                                                  salary   job_type  \
10741  £9000-£12,000 per session depending on experience  Permanent   

                    working_pattern pay_scheme pay_band       staff_group  \
10741  Negotiable Mon-Sun 8am - 8pm      Other      NaN  Medical & Dental   

      specialty                                   full_description  \
10741        GP  Care Quality Commission rated ‘Good’ by the CQ...   

       json_salary_max  json_salary_min json_salary_unit  \
10741        9000000.0          12000.0             YEAR   

                                       json_salary_value  \
10741  £9000-£12,000 per session depending on experience   

               json_date_posted  \
10741  2019-06-10T10:07:10+0100   

                                        json_description json_employment_type  \
10741  &lt;ul&gt;\n&lt;li&gt;\n&lt;p&gt;&lt;strong&gt...            FULL_TIME   

                                    json_hire_name json_address_locality  \
10741  Central Advertising - General Practitioners              Hounslow   

      json_address_postcode  json_lat  json_lng  \
10741               TW3 1NL   51.4711   -0.3621   

                                    json_title json_closing_date  \
10741  Salaried GP Practitioner (2-4 sessions)  31/01/2020 23:59   

              scrape_dt  
10741  10/06/2019 10:30

Okay, someone definitely added a bit more zeroes than usual in the json_salary max column. 3 more zeroes to be precise.

Anyways , moving on...

While we have 29 columns in the dataset , describe gives us information for only 4 columns. This is especially worse if your dataset is riddled with issues as we saw above. 

Introducing the new method, *drumroll*

Pandas Profiling.

Here's how its used.



In [5]:
!pip install pandas_profiling
import pandas_profiling

I am getting the requirement already satisfied message because I already installed it previously. You will have probably have to download the library.

Now that we have imported it, lets use it.

In [6]:
start = time.time()
pandas_profiling.ProfileReport(nhs)
end = time.time()
# To record time taken for execution
ptime = end - start
pandas_profiling.ProfileReport(nhs)

And Voila! , right off the bat, we see that we have 36732 missing entries and 98 duplicate entries.

We also see a ton of very useful information regarding the categorical variables :

1.  department has 3631 (13.2%) missing values
    pay_band has 11642 (42.4%) missing values	
    working_pattern has 4442 (16.2%) missing values	

2.  staff_group has constant value "Medical & Dental" which shows that this column is quite useless and can be dropped.

We also see that a ton of other information regarding the columns including missing values in depth, correlations and so on.



Compared to describe() , this method is significantly better right?

For the most part yes. The information provided is much more and easily understandable compared to describe().

However , while this dataset is definitely not big (27482 rows) , it still took quite a lot of time to generate the report.

Let us compare the values.

In [7]:
print ("Time taken for describe to execute : ",dtime)
print ("Time taken for pandas profiling to execute : ",ptime)

Time taken for describe to execute :  0.020943880081176758
Time taken for pandas profiling to execute :  34.24287462234497


A difference of 30 seconds is definitely something that cannot be ignored. The time taken would further increase to larger datasets to a point where it is not feasible enough to use this method.

## Conclusion

While pandas profiling is excellent for smaller datasets , it is definitely not recommended for larger ones as the time taken is significantly high. 